services:
  db:
    image: postgres:16
    container_name: smartvend-db
    environment:
      POSTGRES_DB: javabrew
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: maven:3.9-eclipse-temurin-21
    container_name: smartvend-app
    depends_on:
      - db
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: mvn clean compile exec:java -Dexec.mainClass="com.smartvend.app.Main"
    environment:
      DB_URL: jdbc:postgresql://db:5432/javabrew
      DB_USER: postgres
      DB_PASS: postgres

  # (opzionale) Adminer per DB browser
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data:
