services:
  db:
    image: postgres:16
    container_name: smartvend-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    # esponi la porta della tua app Java solo se serve:
    # ports:
    #   - "8080:8080"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data:
