create table Admin (
    id bigint generated by default as identity,
    user_id bigint not null unique,
    primary key (id)
);

create table app_user (
    role smallint not null check (role between 0 and 3),
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    name varchar(255) not null,
    password varchar(255) not null,
    surname varchar(255) not null,
    primary key (id)
);

create table ConcreteVendingMachine (
    capacity integer not null,
    createdAt timestamp(6) with time zone not null,
    lastMaintenance timestamp(6) with time zone not null,
    location varchar(255) not null,
    serialNumber varchar(255) not null,
    status varchar(255) not null check (status in ('Operative','OutOfService','Connected')),
    vending_machine_model varchar(255),
    primary key (serialNumber)
);

create table Connection (
    id bigint generated by default as identity,
    start timestamp(6) with time zone not null,
    user_id bigint not null unique,
    machine_id varchar(255) not null unique,
    primary key (id)
);

create table Customer (
    balance float(53) not null,
    id bigint generated by default as identity,
    user_id bigint not null unique,
    primary key (id)
);

create table Inventory (
    occupiedSpace integer not null,
    id bigint generated by default as identity,
    machine_id varchar(255) unique,
    primary key (id)
);

create table Item (
    position integer not null,
    price float(53) not null,
    quantity integer not null,
    volume integer not null,
    createdAt timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    inventory_id bigint not null,
    description varchar(255) not null,
    name varchar(255) not null,
    type varchar(255) not null check (type in ('Snack','Bottle','ExpressBeverage')),
    primary key (id)
);

create table MaintenanceReport (
    id bigint generated by default as identity,
    issueDate timestamp(6) with time zone not null,
    issueDescription varchar(255) not null,
    machine_id varchar(255),
    primary key (id)
);

create table Task (
    assignedAt timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    report_id bigint not null unique,
    supervisor_id bigint,
    worker_id bigint,
    status varchar(255) not null check (status in ('Reported','Assigned','Completed','InProgress','Deleted')),
    primary key (id)
);

create table Transaction (
    initialBalance float(53) not null,
    updatedBalance float(53) not null,
    customer_id bigint,
    date timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    paymentMethod varchar(255) not null check (paymentMethod in ('Card','Cash','Wallet')),
    primary key (id)
);

create table TransactionItem (
    amount float(53) not null,
    id bigint generated by default as identity,
    item_id bigint unique,
    transaction_id bigint,
    machine_id varchar(255),
    primary key (id)
);

create table VendingMachine (
    modelNumber varchar(255) not null,
    type varchar(255) not null check (type in ('Coffe','Snack','PizzoneFarcito')),
    primary key (modelNumber)
);

create table Worker (
    isActive boolean not null,
    id bigint generated by default as identity,
    user_id bigint not null unique,
    primary key (id)
);

alter table if exists Admin 
   add constraint FK13g34xh1kbtwtu93v7a4u0m25 
   foreign key (user_id) 
   references app_user;

alter table if exists ConcreteVendingMachine 
   add constraint FKh8orsc07tnro7r35sxme196n8 
   foreign key (vending_machine_model) 
   references VendingMachine;

alter table if exists Connection 
   add constraint FK1b4h5af9uxs5jutqwr0iyhsck 
   foreign key (machine_id) 
   references ConcreteVendingMachine;

alter table if exists Connection 
   add constraint FKtj4qjyc7ytwsueifx3n4qqgqr 
   foreign key (user_id) 
   references app_user;

alter table if exists Customer 
   add constraint FKksdjlior8xvgvskvb1d3qomuv 
   foreign key (user_id) 
   references app_user;

alter table if exists Inventory 
   add constraint FKlv0h7v1uuiwl8v7s4wn401h1i 
   foreign key (machine_id) 
   references ConcreteVendingMachine;

alter table if exists Item 
   add constraint FKo9snmc7jt9iuowf7h3egadwov 
   foreign key (inventory_id) 
   references Inventory;

alter table if exists MaintenanceReport 
   add constraint FKjckfcg7uix2ce31x8mrhsq39k 
   foreign key (machine_id) 
   references ConcreteVendingMachine;

alter table if exists Task 
   add constraint FKppsob1ngl7dh137tbl5j1qp5h 
   foreign key (report_id) 
   references MaintenanceReport;

alter table if exists Task 
   add constraint FKlj79e9gi8y0xyg9lx8fjil726 
   foreign key (supervisor_id) 
   references Admin;

alter table if exists Task 
   add constraint FK1imufq62jdmtd22nxovh4nxua 
   foreign key (worker_id) 
   references Worker;

alter table if exists Transaction 
   add constraint FKc3nqxp1ym216vsyi7wmdybinr 
   foreign key (customer_id) 
   references Customer;

alter table if exists TransactionItem 
   add constraint FKdws1hkwysgmlwj71mv1xsysnc 
   foreign key (item_id) 
   references Item;

alter table if exists TransactionItem 
   add constraint FKloegib891vuwd9rhkvvff2i59 
   foreign key (machine_id) 
   references ConcreteVendingMachine;

alter table if exists TransactionItem 
   add constraint FKafyl8m6dv49my8lovopmav1ud 
   foreign key (transaction_id) 
   references Transaction;

alter table if exists Worker 
   add constraint FKcqro486q290g2pw0l2ac5820c 
   foreign key (user_id) 
   references app_user;
